
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 9.1.2 EDK_J.12.5.1
* DO NOT EDIT.
*
* Copyright (c) 2008 Xilinx, Inc.  All rights reserved.
*
* Description: Driver configuration
*
*******************************************************************/

#include <pkgconf/hal_microblaze_platform.h>
#include "xparameters.h"
#include "xlltemac.h"

/*
* The configuration table for devices
*/

XLlTemac_Config XLlTemac_ConfigTable[] = {
	{
	 0,
	 MON_TEMAC_0_BASEADDR,
	 1,
	 1,
	 1,
	 0,0,0,0,0,0,0,0,
	 2,//XPAR_XPS_LL_TEMAC34_0_LLINK0_CONNECTED_TYPE,
	 MON_DMA_EMAC_BASEADDR,
	 0,0,0
	}
};
