#!/bin/sh

#exit codes
# -1 - source eCos distribution
# -2 - missing directories
# -3 - platform with the same name exists in distribution


if [ "${ECOS_REPOSITORY}" == "" -o ${ECOS_BSP} == "" ]; then
	echo "Please source proj/env.sh scripts"
	exit -1
fi;

DB_FILE="ecos.db"

BSP_GEN_PATH="microblaze_0/libsrc/${ECOS_BSP}"
DB_FILE_PATH="${BSP_GEN_PATH}/${DB_FILE}"

function file_test {
	if [ ! -d ${BSP_GEN_PATH}  ]; then
		echo "Please run this script inside project or generate library"
		exit -2
	fi
}

function testing_platform {
	PLATFORM_NAME=`cat ${DB_FILE_PATH} | head -n 1`
	if [ `grep "${PLATFORM_NAME}" ${ECOS_REPOSITORY}/${DB_FILE} | wc -l` != 0 ]; then
		echo "Your platform with the same name is in eCos distribution"
		exit -3
	fi
}

echo "Distribution is set corectly"

# testing if you generate file successfully
file_test

testing_platform

#adding platform to file
cat ${DB_FILE_PATH} >> ${ECOS_REPOSITORY}/${DB_FILE}

#copy config directory
cp -R ${BSP_GEN_PATH}/hal ${ECOS_REPOSITORY}
cp -R ${BSP_GEN_PATH}/../../include ${ECOS_REPOSITORY}/hal/microblaze/`ls ${BSP_GEN_PATH}/hal/microblaze`/current

echo "Success"
echo "Thank you for using this simple script"
